Return-Path: <mail@youpharm.co>
Delivered-To: lobo@lerch.org
Received: from mail.eler.ch
	by mail.eler.ch with LMTP
	id BJ9kLnLDm2aYDgQAyA9pPg
	(envelope-from <mail@youpharm.co>)
	for <lobo@lerch.org>; Sat, 20 Jul 2024 14:02:26 +0000
Received: from youpharm.co (youpharm.co [5.101.65.218])
	by mail.eler.ch (Postfix) with ESMTP id E3C9F467AB
	for <emil@lerch.org>; Sat, 20 Jul 2024 14:02:25 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=s1; d=youpharm.co;
 h=Message-ID:From:To:Subject:Date:MIME-Version:Content-Type; i=abuse@youpharm.co;
 bh=Lnj6s7dL4V4gz92hab9GJ0HxEL8=;
 b=MLiLXLaBVkYaJuabi+DsOFUkjmqsYJ0hsfHW5JKX61Fal+1j2iFjFWrggCv+m0zruA+j6W+iJ7CV
   nxcDpT5mZe0+e2bOu1f8YEGNj7DPVpkYjeB8esR4qo/LSot0TIOU7YojSk8HP/hQVYEwpC58f21C
   sXgqEyMn1bV4+UHE1QnhoyZRP/lyadba4SCCSeyG5VQMZ4cIZtlcBFA+yd6I03lZ2f/Lh7tinFXj
   HrOyPjQLpk4VNbVsbbpsI+sKOEGlmgpRVIatV+Hcwk8ZuhFsubdF/cSc1p3jFbUdhBa3TMcqFVS2
   L1UO4e13PWJVjHzAUXlGDF66PGIR2pHnBd1pew==
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=s1; d=youpharm.co;
 b=fFAj5RzuUx0++wASk/u6T0GlBurb2y6h/1WEls22gWKfoEKHzChyXYJNyknfho2r/3Cw0DNrWXFI
   nRIivnoNX4rOvc4hsCieljl9lt0fOaYzLgHKS083D8JIYLLySX0Qwj7xydC3nB3WmHhOlrz6eM7d
   lPIOT14K1e5LxQTLox8PaUqknSUNrsBZ8tREcVLqb7Ud9SVvdHjyccjampV70XPOeKMd9NLt4a/H
   sEeS184PGBo7/uAuHojS2y2LDkY6nRdZPmjPvA9ghNU8udr+biG3NEX8V2v2ZJy7w9H6FfJfCb2/
   MrxZmGPWgcYJ7cQ/pNMKcHM1QoAKYKMEG76V8g==;
Message-ID: <8afeb74dca321817e44e07ac4a2e040962e86e@youpharm.co>
From: Top Medications <mail@youpharm.co>
To: emil@lerch.org
Subject: ***SPAM*** Tablets without a prescription
Date: Sat, 20 Jul 2024 16:02:18 +0200
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="08044db730c8e2ed1eb4fd56b0d4fef3d9e86e"
X-Rspamd-Queue-Id: E3C9F467AB
X-Rspamd-Server: mail.eler.ch
X-Spamd-Result: default: False [10.00 / 11.00];
	ABUSE_SURBL(5.50)[youpharm.co:helo,youpharm.co:dkim,youpharm.co:rdns];
	RSPAMD_URIBL(4.50)[unmaskfauci.com:url];
	BAD_REP_POLICIES(0.10)[];
	MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	DKIM_TRACE(0.00)[youpharm.co:+];
	ARC_NA(0.00)[];
	DMARC_POLICY_ALLOW(0.00)[youpharm.co,none];
	RCVD_COUNT_ZERO(0.00)[0];
	MIME_TRACE(0.00)[0:+,1:+,2:~];
	FROM_EQ_ENVFROM(0.00)[];
	RCPT_COUNT_ONE(0.00)[1];
	TO_DN_NONE(0.00)[];
	R_SPF_ALLOW(0.00)[+a];
	R_DKIM_ALLOW(0.00)[youpharm.co:s=s1];
	ASN(0.00)[asn:34665, ipnet:5.101.65.0/24, country:RU];
	FROM_HAS_DN(0.00)[];
	TO_MATCH_ENVRCPT_ALL(0.00)[];
	DWL_DNSWL_BLOCKED(0.00)[youpharm.co:dkim];
	MID_RHS_MATCH_FROM(0.00)[]
X-Rspamd-Action: rewrite subject
Content-Length: 789

--08044db730c8e2ed1eb4fd56b0d4fef3d9e86e
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable


--08044db730c8e2ed1eb4fd56b0d4fef3d9e86e
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">
</head>
<body><a href=3D"https://unmaskfauci.com/assets/images/chw.php"><img src=3D=
"https://imgpx.com/dfE6oYsvHoYw.png"></a> <div><img width=3D1 height=3D1 =
alt=3D"" src=3D"https://vnevent.net/wp-content/plugins/wp-automatic/awe.p=
hp?QFYiTaVCm0ogM30sC5RNRb%2FKLO0%2FqO3iN9A89RgPbrGjPGsdVierqrtB7w8mnIqJug=
BVA5TZVG%2F6MFLMOrK9z4D6vgFBDRgH88%2FpEmohBbpaSFf4wx1l9S4LGJd87EK6"></div=
></body></html>

--08044db730c8e2ed1eb4fd56b0d4fef3d9e86e--
